"""Daily brief generator.

Produces a markdown intelligence brief from the registry + metrics + findings.
The numbers and findings are fully deterministic; when ANTHROPIC_API_KEY is
available, Claude adds an executive commentary section on top of them (the
model narrates the data — it never produces the data).

Also emits a LinkedIn post draft so the daily automation has ready-to-edit
content in Lucas's voice (see claude-universe/automation/TONE_OF_VOICE.md).
"""

import os
from datetime import datetime

from .cycles import CycleContext
from .metrics import LandscapeMetrics
from .onchain import SpotPrice
from .risk import Finding

DEFAULT_MODEL = os.environ.get("DATPROOF_MODEL", "claude-opus-4-8")


def _fmt_usd(v: float) -> str:
    if v >= 1e9:
        return f"${v / 1e9:,.1f}B"
    if v >= 1e6:
        return f"${v / 1e6:,.1f}M"
    return f"${v:,.0f}"


def render_brief(metrics: LandscapeMetrics, findings: list[Finding],
                 spot: SpotPrice, commentary: str | None = None,
                 cycle_ctx: CycleContext | None = None) -> str:
    now = datetime.utcnow().strftime("%Y-%m-%d")
    lines = [
        f"# DATproof Daily Brief — {now}",
        "",
        f"**BTC spot:** ${spot.usd:,.0f} ({spot.source}, as of {spot.as_of})",
        f"**Tracked corporate BTC:** {metrics.total_btc:,.0f} BTC ({_fmt_usd(metrics.total_value_usd)})",
        f"**Independently verifiable on-chain:** {metrics.verifiable_pct:.1f}%",
        f"**Largest-holder concentration:** {metrics.concentration_top1_pct:.1f}%",
        "",
    ]

    if cycle_ctx is not None:
        lines += [
            "## Cycle context",
            "",
            f"**200-week moving average:** ${cycle_ctx.wma_200w_usd:,.0f} "
            f"(spot is {cycle_ctx.price_to_200wma:.2f}× the long-term trend)",
            f"**vs all-time-high close:** {cycle_ctx.drawdown_from_ath_pct:+.1f}% "
            f"(ATH ${cycle_ctx.ath_usd:,.0f} on {cycle_ctx.ath_date})",
            f"_History: {cycle_ctx.source}, Coinbase Exchange daily candles, "
            f"{cycle_ctx.weeks_of_history} weekly closes, as of {cycle_ctx.as_of}_",
            "",
        ]

    if commentary:
        lines += ["## Executive commentary", "", commentary.strip(), ""]

    lines += [
        "## Holdings snapshot",
        "",
        "| Company | Ticker | BTC | Value | vs avg cost | mNAV | On-chain verifiable |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    for m in metrics.companies:
        c = m.company
        pnl = f"{m.unrealized_pnl_pct:+.1f}%" if m.unrealized_pnl_pct is not None else "n/a"
        mnav = f"{m.mnav:.2f}x" if m.mnav is not None else "n/a"
        verif = "✅" if m.verifiable else "❌"
        lines.append(
            f"| {c.name} | {c.ticker or 'private'} | {c.btc_holdings:,.0f} "
            f"| {_fmt_usd(m.holdings_value_usd)} | {pnl} | {mnav} | {verif} |"
        )

    lines += ["", "## Risk findings", ""]
    if not findings:
        lines.append("_No findings triggered._")
    for f in findings:
        lines += [
            f"### [{f.severity.upper()}] {f.title}",
            f"*Assertion: {f.assertion} · Frameworks: {', '.join(f.frameworks)}*",
            "",
            f.detail,
            "",
        ]

    lines += [
        "---",
        "_Holdings figures are company disclosures as of their stated dates; nothing above is "
        "investment advice. mNAV requires a supplied market cap and is omitted where unsourced. "
        "Generated by [DATproof](https://github.com/lucascashwell3-ai/datproof)._",
        "",
    ]
    return "\n".join(lines)


def render_linkedin_draft(metrics: LandscapeMetrics, findings: list[Finding],
                          spot: SpotPrice) -> str:
    """Post draft grounded in today's data. Intentionally plain — the tone file
    in claude-universe governs final voice; this gives the facts a shape."""
    top = metrics.companies[0].company if metrics.companies else None
    worst = min(
        (m for m in metrics.companies if m.unrealized_pnl_pct is not None),
        key=lambda m: m.unrealized_pnl_pct,
        default=None,
    )
    high_findings = [f for f in findings if f.severity in ("high", "critical")]

    lines = [
        "# LinkedIn draft (edit before posting)",
        "",
        f"Public companies now hold {metrics.total_btc:,.0f} BTC "
        f"({_fmt_usd(metrics.total_value_usd)}). Here's what my audit brain can't ignore:",
        "",
        f"→ Only {metrics.verifiable_pct:.1f}% of it is verifiable on-chain. The rest is "
        "\"trust the 8-K.\" In any other asset class we'd call that an existence-assertion gap.",
    ]
    if top:
        lines.append(
            f"→ {top.name} alone is {metrics.concentration_top1_pct:.0f}% of the corporate "
            "total. That's not a sector, that's a single point of failure with an index ticker."
        )
    if worst is not None and worst.unrealized_pnl_pct < 0:
        lines.append(
            f"→ At ${spot.usd:,.0f} BTC, {worst.company.name} sits "
            f"{abs(worst.unrealized_pnl_pct):.0f}% below its disclosed average cost — and under "
            "ASU 2023-08 that loss hits the income statement, not a footnote."
        )
    if high_findings:
        lines.append(
            f"→ My tool flagged {len(high_findings)} high-severity findings today across "
            f"{len(metrics.companies)} tracked companies."
        )
    lines += [
        "",
        "I built DATproof to run this analysis daily — on-chain verification, mNAV, and "
        "audit-grade risk findings for digital asset treasury companies. Repo in comments.",
        "",
    ]
    return "\n".join(lines)


def generate_commentary(metrics: LandscapeMetrics, findings: list[Finding],
                        spot: SpotPrice, model: str = DEFAULT_MODEL) -> str | None:
    """Claude-written executive commentary. Returns None when no credentials
    are configured, so the pipeline degrades to the deterministic brief."""
    if not os.environ.get("ANTHROPIC_API_KEY"):
        return None

    import anthropic

    top_rows = "\n".join(
        f"- {m.company.name} ({m.company.ticker or 'private'}): {m.company.btc_holdings:,.0f} BTC, "
        f"pnl vs avg cost: {m.unrealized_pnl_pct if m.unrealized_pnl_pct is not None else 'n/a'}, "
        f"verifiable: {m.verifiable}"
        for m in metrics.companies
    )
    findings_txt = "\n".join(f"- [{f.severity}] {f.title}" for f in findings[:10])

    client = anthropic.Anthropic()
    response = client.messages.create(
        model=model,
        max_tokens=1500,
        thinking={"type": "adaptive"},
        system=(
            "You are a risk analyst writing the executive commentary for a daily digital-asset-"
            "treasury intelligence brief read by compliance and risk professionals. Write 2-3 "
            "tight paragraphs. Ground every claim strictly in the data provided — do not invent "
            "figures, events, or news. Plain prose, no headers, no bullet points, no hype."
        ),
        messages=[{
            "role": "user",
            "content": (
                f"BTC spot: ${spot.usd:,.0f} ({spot.source}).\n"
                f"Total tracked corporate BTC: {metrics.total_btc:,.0f} "
                f"(verifiable on-chain: {metrics.verifiable_pct:.1f}%).\n"
                f"Companies:\n{top_rows}\n\nTop findings:\n{findings_txt}"
            ),
        }],
    )
    if response.stop_reason == "refusal":
        return None
    return next((b.text for b in response.content if b.type == "text"), None)
